AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Master CloudFormation Template
  Deploys complete Rails application infrastructure using nested stacks.

############################################################
# PARAMETERS
############################################################

Parameters:

  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment Name

  ProjectName:
    Type: String
    Default: DevOps-Interview-ROR-App
    Description: Project Name

  TemplateBucket:
    Type: String
    Description: S3 Bucket containing nested CloudFormation templates

  RailsImageURI:
    Type: String
    Description: Rails ECR Image URI

  NginxImageURI:
    Type: String
    Description: Nginx ECR Image URI

  DBUsername:
    Type: String
    Default: postgres

  DBPassword:
    Type: String
    NoEcho: true

############################################################
# METADATA
############################################################

Metadata:

  AWS::CloudFormation::Interface:

    ParameterGroups:

      - Label:
          default: Project Configuration
        Parameters:
          - ProjectName
          - EnvironmentName

      - Label:
          default: CloudFormation Templates
        Parameters:
          - TemplateBucket

      - Label:
          default: Container Images
        Parameters:
          - RailsImageURI
          - NginxImageURI

      - Label:
          default: Database
        Parameters:
          - DBUsername
          - DBPassword

############################################################
# RESOURCES
############################################################

Resources:

############################################################
# VPC STACK
############################################################

  NetworkStack:

    Type: AWS::CloudFormation::Stack

    Properties:

      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/network/vpc.yaml
        - Bucket: !Ref TemplateBucket

      TimeoutInMinutes: 20

      Parameters:

        EnvironmentName: !Ref EnvironmentName

        ProjectName: !Ref ProjectName

############################################################
# SECURITY GROUP STACK
############################################################

  SecurityStack:

    Type: AWS::CloudFormation::Stack

    DependsOn:

      - NetworkStack

    Properties:

      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/security/security-groups.yaml
        - Bucket: !Ref TemplateBucket

      TimeoutInMinutes: 20

      Parameters:

        EnvironmentName: !Ref EnvironmentName

        ProjectName: !Ref ProjectName

        VpcId: !GetAtt NetworkStack.Outputs.VpcId

############################################################
# S3 STACK
############################################################

  StorageStack:

    Type: AWS::CloudFormation::Stack

    Properties:

      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/storage/s3.yaml
        - Bucket: !Ref TemplateBucket

      TimeoutInMinutes: 20

      Parameters:

        EnvironmentName: !Ref EnvironmentName

        ProjectName: !Ref ProjectName
############################################################
# IAM NESTED STACK
############################################################

  IAMStack:

    Type: AWS::CloudFormation::Stack

    DependsOn:
      - StorageStack

    Properties:

      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/iam/iam.yaml
        - Bucket: !Ref TemplateBucket

      TimeoutInMinutes: 20

      Parameters:

        EnvironmentName: !Ref EnvironmentName

        ProjectName: !Ref ProjectName

        S3BucketName: !GetAtt StorageStack.Outputs.BucketName

############################################################
# DATABASE (RDS) NESTED STACK
############################################################

  DatabaseStack:

    Type: AWS::CloudFormation::Stack

    DependsOn:
      - NetworkStack
      - SecurityStack

    Properties:

      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/database/rds.yaml
        - Bucket: !Ref TemplateBucket

      TimeoutInMinutes: 30

      Parameters:

        EnvironmentName: !Ref EnvironmentName

        ProjectName: !Ref ProjectName

        VpcId: !GetAtt NetworkStack.Outputs.VpcId

        PrivateSubnetA: !GetAtt NetworkStack.Outputs.PrivateSubnetAId

        PrivateSubnetB: !GetAtt NetworkStack.Outputs.PrivateSubnetBId

        RDSSecurityGroup: !GetAtt SecurityStack.Outputs.RDSSecurityGroupId

        DBUsername: !Ref DBUsername

        DBPassword: !Ref DBPassword

  ############################################################
# LOAD BALANCER STACK
############################################################

  LoadBalancerStack:

    Type: AWS::CloudFormation::Stack

    DependsOn:

      - NetworkStack
      - SecurityStack

    Properties:

      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/loadbalancer/alb.yaml
        - Bucket: !Ref TemplateBucket

      TimeoutInMinutes: 20

      Parameters:

        EnvironmentName: !Ref EnvironmentName

        ProjectName: !Ref ProjectName

        VpcId: !GetAtt NetworkStack.Outputs.VpcId

        PublicSubnetA: !GetAtt NetworkStack.Outputs.PublicSubnetAId

        PublicSubnetB: !GetAtt NetworkStack.Outputs.PublicSubnetBId

        ALBSecurityGroup: !GetAtt SecurityStack.Outputs.ALBSecurityGroupId  
  ############################################################
# ECS STACK
############################################################

  ECSStack:

    Type: AWS::CloudFormation::Stack

    DependsOn:

      - IAMStack
      - DatabaseStack
      - LoadBalancerStack

    Properties:

      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/ecs/cluster.yaml
        - Bucket: !Ref TemplateBucket

      TimeoutInMinutes: 30

      Parameters:

        EnvironmentName: !Ref EnvironmentName

        ProjectName: !Ref ProjectName

        VpcId: !GetAtt NetworkStack.Outputs.VpcId

        PrivateSubnetA: !GetAtt NetworkStack.Outputs.PrivateSubnetAId

        PrivateSubnetB: !GetAtt NetworkStack.Outputs.PrivateSubnetBId

        ECSSecurityGroup: !GetAtt SecurityStack.Outputs.ECSSecurityGroupId

        ExecutionRoleArn: !GetAtt IAMStack.Outputs.ECSTaskExecutionRoleArn

        TaskRoleArn: !GetAtt IAMStack.Outputs.ECSTaskRoleArn

        TargetGroupArn: !GetAtt LoadBalancerStack.Outputs.TargetGroupArn

        LBEndpoint: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNS

        RDSHostname: !GetAtt DatabaseStack.Outputs.DBEndpoint

        RDSPort: !GetAtt DatabaseStack.Outputs.DBPort

        RDSDBName: !GetAtt DatabaseStack.Outputs.DBName

        RDSUsername: !Ref DBUsername

        RDSPassword: !Ref DBPassword

        S3BucketName: !GetAtt StorageStack.Outputs.BucketName

        RailsImage: !Ref RailsImageURI

        NginxImage: !Ref NginxImageURI    

############################################################
# OUTPUTS
############################################################

Outputs:

  VpcId:

    Description: VPC ID

    Value: !GetAtt NetworkStack.Outputs.VpcId

  ALBDNSName:

    Description: Application Load Balancer DNS

    Value: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNS

  S3BucketName:

    Description: Application S3 Bucket

    Value: !GetAtt StorageStack.Outputs.BucketName

  DatabaseEndpoint:

    Description: PostgreSQL Endpoint

    Value: !GetAtt DatabaseStack.Outputs.DBEndpoint

  DatabaseName:

    Description: PostgreSQL Database Name

    Value: !GetAtt DatabaseStack.Outputs.DBName

  ECSExecutionRole:

    Description: ECS Task Execution Role

    Value: !GetAtt IAMStack.Outputs.ECSTaskExecutionRoleArn

  ECSTaskRole:

    Description: ECS Task Role

    Value: !GetAtt IAMStack.Outputs.ECSTaskRoleArn